### ISSUE TITLE
ISSUE: bot isnt working anymore 

### ISSUE THREAD

**Issue by Mattias16-beep** [adityafajrip/GetGrassNotifier#1]
Hello Sir, 

I was using your script since a week now and it was working perfectly. 

Suddenly the script isnt workign anymore i think getgrass changed the way of fetching the data from the api. 

Did you find a way to solve it ? 

Thanks.

**Comment by adityafajrip** [comment]
Hi,

Thanks for letting me know. I’m aware of the issue, and I’m still working on a fix.

I’ll update the repo as soon as it’s solved.

**Comment by adityafajrip** [comment]
Hey @Mattias16-beep,

The bot is up and running again! I've fixed the API data fetching, and I also removed the Get Country Flag function.

Just a heads-up, the todayEarning isn't updating on the Grass API right now, so I'm still showing the data even though it’s not updated.

Thanks a lot for reporting the issue! Feel free to open a new issue if you encounter any other problems, and don't forget to pull the latest changes.
